### ISSUE TITLE
Crash in version 0.2

### ISSUE THREAD

**Issue by gavol** [ratbuddy/ratbuddyssey#1]
Version 0.2 crashes as soon as I select a speaker using the following ady file:

[xt32.zip](https://github.com/ratbuddy/ratbuddyssey/files/2538479/xt32.zip)

Thanks for your very hard and nice work.

**Comment by ratbuddy** [comment]
I will investigate, thanks for the report.

**Comment by Stefc13** [comment]
Hello,

I have the same issue with the files coming from my Marantz 7012.

[NewPosition20181103org.zip](https://github.com/ratbuddy/ratbuddyssey/files/2561315/NewPosition20181103org.zip)

You app is very promising !!! 

Thanks

**Comment by gavol** [comment]
Let me add that I have the issue with Win7, while the application does not crash in Win10.

**Comment by ratbuddy** [comment]
Ahh, I don't have any Windows 7 machines any more, not sure how I can
test that. Let me see about adding crash error output at least.

**Comment by Stefc13** [comment]
On my side it happens on W10 1803. I will try on another machine et give you a feedback then....

**Comment by Stefc13** [comment]
Same result with my other PC same windows version. 
FYI my config is 5.1

**Comment by ratbuddy** [comment]
OK, I will look tonight, thank you!

**Comment by gavol** [comment]
I have found some additional information and it looks like the application terminated because of some not handled exception:

Application: Ratbuddyssey.exe
Framework version: v4.0.30319
Description: process terminated because of a unhandled exception.
Exception information: System.FormatException
   in System.Number.StringToNumber(System.String, System.Globalization.NumberStyles, NumberBuffer ByRef, System.Globalization.NumberFormatInfo, Boolean)
   in System.Number.ParseDecimal(System.String, System.Globalization.NumberStyles, System.Globalization.NumberFormatInfo)
   in Ratbuddyssey.RatbuddysseyHome.DrawChart(Ratbuddyssey.DetectedChannel)
   in Ratbuddyssey.RatbuddysseyHome.ChannelsView_SelectionChanged(System.Object, System.Windows.Controls.SelectionChangedEventArgs)
   in System.Windows.Controls.SelectionChangedEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   in System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   in System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   in System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   in System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   in System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs)
   in System.Windows.Controls.ListBox.OnSelectionChanged(System.Windows.Controls.SelectionChangedEventArgs)
   in System.Windows.Controls.Primitives.Selector.InvokeSelectionChanged(System.Collections.Generic.List`1<ItemInfo>, System.Collections.Generic.List`1<ItemInfo>)
   in System.Windows.Controls.Primitives.Selector+SelectionChanger.End()
   in System.Windows.Controls.Primitives.Selector+SelectionChanger.SelectJustThisItem(ItemInfo, Boolean)
   in System.Windows.Controls.ListBox.MakeSingleSelection(System.Windows.Controls.ListBoxItem)
   in System.Windows.Controls.ListBox.NotifyListItemClicked(System.Windows.Controls.ListBoxItem, System.Windows.Input.MouseButton)
   in System.Windows.Controls.ListBoxItem.HandleMouseButtonDown(System.Windows.Input.MouseButton)
   in System.Windows.Controls.ListBoxItem.OnMouseLeftButtonDown(System.Windows.Input.MouseButtonEventArgs)
   in System.Windows.UIElement.OnMouseLeftButtonDownThunk(System.Object, System.Windows.Input.MouseButtonEventArgs)
   in System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   in System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   in System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   in System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   in System.Windows.UIElement.ReRaiseEventAs(System.Windows.DependencyObject, System.Windows.RoutedEventArgs, System.Windows.RoutedEvent)
   in System.Windows.UIElement.OnMouseDownThunk(System.Object, System.Windows.Input.MouseButtonEventArgs)
   in System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   in System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   in System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   in System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   in System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   in System.Windows.UIElement.RaiseTrustedEvent(System.Windows.RoutedEventArgs)
   in System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs, Boolean)
   in System.Windows.Input.InputManager.ProcessStagingArea()
   in System.Windows.Input.InputManager.ProcessInput(System.Windows.Input.InputEventArgs)
   in System.Windows.Input.InputProviderSite.ReportInput(System.Windows.Input.InputReport)
   in System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr, System.Windows.Input.InputMode, Int32, System.Windows.Input.RawMouseActions, Int32, Int32, Int32)
   in System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr, MS.Internal.Interop.WindowMessage, IntPtr, IntPtr, Boolean ByRef)
   in System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   in MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   in MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   in System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   in System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   in System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   in MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   in MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   in System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   in System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   in System.Windows.Application.RunDispatcher(System.Object)
   in System.Windows.Application.RunInternal(System.Windows.Window)
   in System.Windows.Application.Run(System.Windows.Window)
   in Ratbuddyssey.App.Main()

**Comment by PierreHss** [comment]
I have the same issue with my Marantz 6012 files
[251118appli.zip](https://github.com/ratbuddy/ratbuddyssey/files/2637177/251118appli.zip)

**Comment by ratbuddy** [comment]
Haven't been able to reproduce yet, sorry!

**Comment by fhriley** [comment]
In Windows, switch your number settings to something other than english. Pick something that formats numbers with commas instead of decimal points. I bet that will reproduce it.

**Comment by PierreHss** [comment]
fhriley, you win ! thank you a lot !!
