### ISSUE TITLE
Crash in version 0.2.1

### ISSUE THREAD

**Issue by sramsay100** [ratbuddy/ratbuddyssey#2]
Many thanks for your hard work. I haven’t fully tried this app yet but it is a must considering the vast lack of functionality of the Audyssey App.

I would like to report that when you select a measurement to be displayed on the graph that doesn't exist, the app crashes. My ADY file contains 3 measurements (the bare minimum the app allows you to take) and when clicking on measurement 4, it app crashes and exits.

[Sofa Forward Solo.zip](https://github.com/ratbuddy/ratbuddyssey/files/3145865/Sofa.Forward.Solo.zip)

May I suggest a simple IF statement that detects the number of measurements and ghosts/disables the selectable check boxes in UI for those which aren’t available. A small bug nonetheless, one that can easily be fixed if you has time.
Hope this helps.

**Comment by ratbuddy** [comment]
I will look at this, thank you.

**Comment by sramsay100** [comment]
Hi RatBuddy. I would like to contribute more to say thank you for a great little App. I have found it really useful so far. I have found five more small bugs which I think would be a really simple and quick fix for you to recode. One of them makes a huge difference for me and I personally believe it fills in a huge hole in the Editor App for those looking to edit a flat target curve instead of reference one.

I'm happy to debug to find the solution for you before commenting here in 'Issues', if this helps at all. Unless you prefer me to message you directly somehow?

Look forward to hearing back from you on this.

Steve

**Comment by ratbuddy** [comment]
Whatever you prefer.. if you want to go ahead and fix anything, I will be
happy to review any pull requests as well.

**Comment by sramsay100** [comment]
Sorry buddy I meant to mention that I haven’t coded with C# in over a decade and don’t have the confidence to recode your work. If however, this is the only contribution you are looking for then then I understand as I agree that GitHub is designed for contributions from developers.

**Comment by ratbuddy** [comment]
Not at all, I just wanted to let you know that any help is welcomed,
whether it be reporting bugs, testing, coding, or just plain suggestions.
I'm not picky or proud :)
